// Auto-generated
let project = new Project('untitled');

project.addSources('Sources');
project.addLibrary("/Applications/Blender.app/armsdk/armory");
project.addLibrary("/Applications/Blender.app/armsdk/iron");
project.addLibrary("/Applications/Blender.app/armsdk/lib/haxebullet");
project.addAssets("/Applications/Blender.app/armsdk/lib/haxebullet/ammo/ammo.js", { notinlist: true });
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.CubeController');
project.addParameter("--macro keep('arm.CubeController')");
project.addParameter('arm.SaveLoadMechanism');
project.addParameter("--macro keep('arm.SaveLoadMechanism')");
project.addParameter('armory.trait.internal.CanvasScript');
project.addParameter("--macro keep('armory.trait.internal.CanvasScript')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders("build_untitled/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_untitled/compiled/Assets/**", { notinlist: true });
project.addAssets("build_untitled/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("Bundled/canvas/SaveLoad.files", { notinlist: true });
project.addAssets("Bundled/canvas/SaveLoad.json", { notinlist: true });
project.addAssets("Bundled/save_game.json", { notinlist: true });
project.addShaders("/Applications/Blender.app/armsdk/armory/Shaders/debug_draw/**");
project.addParameter('--times');
project.addLibrary("/Applications/Blender.app/armsdk/lib/zui");
project.addAssets("/Applications/Blender.app/armsdk/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');


resolve(project);
